### ISSUE TITLE
用phpstorm打开看到有两个叫swoole_table的类

### ISSUE THREAD

**Issue by zzsme** [EagleWu/swoole-auto-complete#12]
用phpstorm打开看到有两个叫swoole_table的类，
提问：为什么要有两个相同的类呢？

**Comment by zzsme** [comment]
在1144行和1175行

**Comment by EagleWu** [comment]
感谢 反馈，最新版本 1ce9e0bbe705d6ecce7469dd91988fe3de070a7f 已修复
